minor changes

diff --git a/launch-confedit b/launch-confedit
--- a/launch-confedit
+++ b/launch-confedit
@@ -4,10 +4,11 @@
 set -euo pipefail
 
 # Check if the configuration file exists, and if it does, source it
-if [ -f "$HOME/scripts/dmenu/config/config" ]; then
-  . "$HOME/scripts/dmenu/config/config"
+if [ -f "$HOME/scripts/_launch-helper.sh" ]; then
+  . "$HOME/scripts/config/_launch-helper.sh"
 else
-  echo "configuration file not found" && exit 1
+  echo "configuration file not found"
+  exit 1
 fi
 
 main() {
diff --git a/launch-kill b/launch-kill
--- a/launch-kill
+++ b/launch-kill
@@ -4,11 +4,13 @@
 set -euo pipefail
 
 # Check if the configuration file exists, and if it does, source it
-if [ -f "$HOME/scripts/dmenu/config/config" ]; then
-  . "$HOME/scripts/dmenu/config/config"
+if [ -f "$HOME/scripts/_launch-helper.sh" ]; then
+  . "$HOME/scripts/config/_launch-helper.sh"
 else
-  echo "configuration file not found" && exit 1
+  echo "configuration file not found"
+  exit 1
 fi
+
 
 # Get selected process and confirm killing it.
 selected=$(ps --user "$USER" -F | ${DMENU} "Search for process to kill:" "$@" | awk '{print $2" "$11}')
