minor changes

diff --git a/menu-kill b/menu-kill
--- a/menu-kill
+++ b/menu-kill
@@ -1,14 +1,27 @@
 #!/usr/bin/env bash
 
-# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
+# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
+# if certain things happen, which is a good thing.  Otherwise, we can
+# get hidden bugs that are hard to discover.
 set -euo pipefail
 
-. "$HOME/scripts/_menu-helper.sh" || exit 1
+# script will not hit this if there is no config-file to load
+# shellcheck disable=SC1090
+. ~/scripts/config/config || exit 1
 
-# Get selected process and confirm killing it.
-selected=$(ps --user "$USER" -F | ${LAUNCHER} "Search for process to kill:" "$@" | awk '{print $2" "$11}')
-[[ -z "$selected" ]] && exit 1
-answer=$(echo -e "No\nYes" | ${LAUNCHER} "Kill $selected?" "$@")
-[[ "$answer" == "Yes" ]] && kill -9 "${selected%% *}" && echo "Process $selected has been killed." && exit 0
-echo "Program terminated." && exit 1
+main() {
+    # Running ps to get running processes and display in dmenu.
+    # In this script we use a variable called $LAUNCHER, in your scripts, you
+    # should just write dmenu or rofi or whatever launcher you use.
+    selected=$(ps --user "$USER" -F | awk '{print $2" "$11$12}' | ${LAUNCHER} " Search process to kill:" "$@")
+    
+    [[ -n "$selected" ]] && answer=$(echo -e "No\nYes" | ${LAUNCHER} "Kill $selected?" "$@")
 
+    if [[ "$answer" == "Yes" ]]; then
+    kill -9 "${selected%% *}" && echo "Process $selected has been killed." && exit 0
+    else
+    echo "Program terminated." && exit 1
+fi
+}
+
+[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
