minor changes

diff --git a/dmenu/dm-confedit b/dmenu/dm-confedit
--- a/dmenu/dm-confedit
+++ b/dmenu/dm-confedit
@@ -1,19 +1,14 @@
 #!/usr/bin/env bash
-#
-# Script name: dm-confedit
-# Description: Choose from a list of configuration files to edit.
-# Dependencies: dmenu, emacsclient
-# GitLab: https://www.gitlab.com/dwt1/dmscripts
-# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
-# Contributors: Derek Taylor
-#               Simon Ingelsson
-#               HostGrady
 
-# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
-# if certain things happen, which is a good thing.  Otherwise, we can
-# get hidden bugs that are hard to discover.
+# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
 set -euo pipefail
-source "$HOME/scripts/dmenu/config/config"
+
+# Check if the configuration file exists, and if it does, source it
+if [ -f "$HOME/scripts/dmenu/config/config" ]; then
+  . "$HOME/scripts/dmenu/config/config"
+else
+  echo "configuration file not found" && exit 1
+fi
 
 main() {
   # Clean options array making sure that the files exist
diff --git a/dmenu/dm-logout b/dmenu/dm-logout
--- a/dmenu/dm-logout
+++ b/dmenu/dm-logout
@@ -1,12 +1,14 @@
 #!/usr/bin/env bash
 
+# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
 set -euo pipefail
-source "$HOME/scripts/dmenu/config/config"
 
-
-# ensure that no packages are being installed
-# check for pacman and paru, yay
-[ -f /var/lib/pacman/db.lck ] && notify-send --urgency=critical "❕[ERROR] /var/lib/pacman/db.lck exists pacman in use" && exit 1
+# Check if the configuration file exists, and if it does, source it
+if [ -f "$HOME/scripts/dmenu/config/config" ]; then
+  . "$HOME/scripts/dmenu/config/config"
+else
+  echo "configuration file not found" && exit 1
+fi
 
 _out="echo"
 if [[ ${TERM} == 'dumb' ]]; then
@@ -15,6 +17,25 @@ fi
 
 output(){
     ${_out} "power-menu" "$@"
+}
+
+warning(){
+  if [ -f /var/lib/pacman/db.lock ]; then
+    ${_out} "pacman is running wait for it to finish"
+  fi
+
+  if pgrep -x "pacman" > /dev/null; then
+    ${_out} "System is updating. Cannot shut down, reboot or log out right now." 
+    exit 1
+  fi
+}
+
+desktop(){
+  case "$XDG_SESSION_TYPE" in
+    'x11') grep "Name=" /usr/share/xsessions/*.desktop | cut -d'=' -f2;;
+    'wayland') grep "Name=" /usr/share/wayland-sessions/*.desktop | cut -d'=' -f2 || grep "Name=" /usr/share/xsessions/*.desktop | grep -i "wayland" | cut -d'=' -f2 | cut -d' ' -f1;; 
+    *) err "Unknown display server";;
+  esac
 }
 
 main() {
@@ -26,20 +47,33 @@ main() {
     "Shutdown"
     "Suspend"
     "Quit"
-    )
+    ) 
+    declare -a MANAGERS
+    while IFS= read -r manager
+    do
+        MANAGERS+=("${manager,,}")
+    done < <(desktop)
 
     choice=$(printf '%s\n' "${options[@]}" | ${DMENU} 'Shutdown menu:' "${@}")
     # What to do when/if we choose one of the options.
     case $choice in
         'Logout')
-            killall Xorg           
+                if [[ "$(echo -e "No\nYes" | ${DMENU} "${choice}?" "${@}" )" == "Yes" ]]; then
+                warning
+                for manager in "${MANAGERS[@]}"; do 
+                killall "${manager}" || output "Process ${manager} was not running."
+                done
+            else
+                output "User chose not to logout." && exit 1
+            fi
             ;;
         'Lock screen')
-            # shellcheck disable=SC2154
-            ${logout_locker}
+          warning
+          ${logout_locker}
             ;;
         'Reboot')
             if [[ "$(echo -e "No\nYes" | ${DMENU} "${choice}?" "${@}" )" == "Yes" ]]; then
+                warning
                 systemctl reboot
             else
                 output "User chose not to reboot." && exit 0
@@ -47,6 +81,7 @@ main() {
             ;;
         'Shutdown')
             if [[ "$(echo -e "No\nYes" | ${DMENU} "${choice}?" "${@}" )" == "Yes" ]]; then
+                warning
                 systemctl poweroff
             else
                 output "User chose not to shutdown." && exit 0
@@ -54,6 +89,7 @@ main() {
             ;;
         'Suspend')
             if [[ "$(echo -e "No\nYes" | ${DMENU} "${choice}?" "${@}" )" == "Yes" ]]; then
+                warning
                 systemctl suspend
             else
                 output "User chose not to suspend." && exit 0
@@ -70,5 +106,4 @@ main() {
     esac
 
 }
-
 [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/dmenu/dm-maim b/dmenu/dm-maim
--- a/dmenu/dm-maim
+++ b/dmenu/dm-maim
@@ -1,14 +1,25 @@
 #!/usr/bin/env bash
 
-# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
-# if certain things happen, which is a good thing.  Otherwise, we can
-# get hidden bugs that are hard to discover.
+# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
 set -euo pipefail
-source "$HOME/scripts/dmenu/config/config"
+
+# Check if the configuration file exists, and if it does, source it
+if [ -f "$HOME/scripts/dmenu/config/config" ]; then
+  . "$HOME/scripts/dmenu/config/config"
+else
+  echo "configuration file not found" && exit 1
+fi
+
+sound(){
+if [ -f /usr/share/sounds/freedesktop/stereo/camera-shutter.oga ];then
+paplay /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
+fi
+}
 
 cp2cb() {
   case "$XDG_SESSION_TYPE" in
-    'x11') xclip -r -selection clipboard;; 
+    'x11') xclip -r -selection clipboard;;
+    'wayland') wl-copy -n;;  
     *) err "Unknown display server";; 
   esac
 }
@@ -106,16 +117,19 @@ main() {
       # shellcheck disable=SC2086,SC2154
       maim ${_maim_args} "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
       notify-send "Saved Screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png"
+      sound
     ;;
     'Clipboard')
       # shellcheck disable=SC2086
       maim ${_maim_args} | cp2cb-maim
       notify-send "Saved Screenshot" "Clipboard"
+      sound
     ;;
     'Both')
       # shellcheck disable=SC2086
       maim ${_maim_args} | tee "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png" | cp2cb-maim
       notify-send "Saved Screenshot" "${maim_dir}/${maim_file_prefix}-${_file_type}-$(get_timestamp).png And Clipboard"
+      sound 
     ;;
     *)
       exit 1
@@ -125,4 +139,3 @@ main() {
 }
 
 [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
-
diff --git a/dmenu/dm-man b/dmenu/dm-man
--- a/dmenu/dm-man
+++ b/dmenu/dm-man
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
 
-# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
-# if certain things happen, which is a good thing.  Otherwise, we can
-# get hidden bugs that are hard to discover.
+# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
 set -euo pipefail
 
+# Check if the configuration file exists, and if it does, source it
+if [ -f "$HOME/scripts/dmenu/config/config" ]; then
+  . "$HOME/scripts/dmenu/config/config"
+else
+  echo "configuration file not found" && exit 1
+fi
 
-# script will not hit this if there is no config-file to load
-# shellcheck disable=SC1090
-source "$HOME/scripts/dmenu/config/config"
 
 function main() {
   # An array of options to choose.
diff --git a/dmenu/dm-radio b/dmenu/dm-radio
--- a/dmenu/dm-radio
+++ b/dmenu/dm-radio
@@ -1,7 +1,14 @@
 #!/usr/bin/env bash
-set -euo pipefail
-source "$HOME/scripts/dmenu/config/config"
 
+# Exit if any command fails, if any undefined variable is used, or if a pipeline fails
+set -euo pipefail
+
+# Check if the configuration file exists, and if it does, source it
+if [ -f "$HOME/scripts/dmenu/config/config" ]; then
+  . "$HOME/scripts/dmenu/config/config"
+else
+  echo "configuration file not found" && exit 1
+fi
 
 menu() {
   printf '%s\n' "Quit"
